### ISSUE TITLE
3 license models?

### ISSUE THREAD

**Issue by DamareYoh** [skerkour/rz#2]
This repo contains:
- [An apache 2.0 license](https://github.com/skerkour/rz/blob/main/LICENSE.txt)
- [An MIT license](https://github.com/skerkour/rz/blob/main/LICENSE_MIT.txt)
- A hard to find link to a GPL3 license in the [README](https://bloom.sh/licensing)

Which of these is the license for this library?

**Comment by skerkour** [comment]
Hello,
I'm sorry for the confusion. I've removed the link from the README.

This project is licensed as `Apache 2.0` but is a fork from a project that is `MIT` licensed and the original author wanted me to include the `MIT` license file, so I respected his choice.

I'm not a lawyer, but as far as I understand, "re-licensing" a project from `MIT` to `Apache 2.0` is possible as these licenses are  compatible, so from what I understand, by using this project you "only" have to respect the `Apache 2.0` license (anyway those 2 licenses are almost identical).
